### ISSUE TITLE
flowStats.R functions return NAs

### ISSUE THREAD

**Issue by lindsayplatt** [USGS-R/trainR#10]
`flowStats.R` functions return NA instead of the statistic. See example below.

```r
mydata <- data.frame(flow=c(1:5, NA), year=2010)
add_annual_median_flow(mydata) @lindsaycarr changed function name to match code
```

Debug and fix so that the functions return real values.

**Comment by lhubbard-USGS** [comment]
Fixed issue #10. Added '@importFrom' for additional functions used.

```r
#' @importFrom dplyr group_by
#' @importFrom plyr mutate
```
