### ISSUE TITLE
Setup tests for assumptions of flowStats.R functions.

### ISSUE THREAD

**Issue by lindsayplatt** [USGS-R/trainR#11]
The flowStats functions...

1. only accept data frames as input.
2. argument `flowTS` must have numeric column for streamflow called "flow".
3. argument `flowTS` must have numeric column with a 4-digit year called "year".
4. return a data frame with a new column called "flow_pk", "flow_med", or "flow_low".

**Comment by lhubbard-USGS** [comment]
added tests for flow_stats function
