### ISSUE TITLE
Check assumptions of inputs for flowStats.R

### ISSUE THREAD

**Issue by lindsayplatt** [USGS-R/trainR#12]
Fail fast and helpfully if the inputs to these functions are not correct. Assumptions: data.frame with two numeric columns called "flow" and "year".

**Comment by lhubbard-USGS** [comment]
fixed #12 by adding stop message

```r
if(!is.data.frame(flow.ts) || any(names(flow.ts) != c('flow', 'year'))) {
    stop("flow.ts must be a data.frame with columns 'flow' and 'year'")
  }
```
