### ISSUE TITLE
sep_censored is ignoring right-censored values

### ISSUE THREAD

**Issue by lindsayplatt** [USGS-R/trainR#31]
`sep_censored` correctly identifies left censored values, but drop right-censored

```r
sep_censored(c("<1", 2, 3, ">9"))
$numeric.vals
[1] 1 2 3 9

$censored
[1] "<" NA  NA  NA 
```

The final value of `$censored` should be ">", not NA.

**Comment by rbcarvin** [comment]
the which_censored function did not include greater than (">"):
```r
which_censored <- function(vals){
  grep("<", vals)
}
```
Added greater than to this function:
```r
which_censored <- function(vals){
  grep("<|>", vals)
}
```
